### ISSUE TITLE
Byproduct reconstruction mesh files

### ISSUE THREAD

**Issue by lwtai** [zju3dv/gcasp#12]
Hi, I'm wondering if the mesh files are contained in the result generate by eval.py, or I need to find ways to generate them manually?
Also, I met a problem when I try to generate result by instruction provided in README, which the eval.py only generate empty folder, could you kindly tell me where is the problem?
Thank you!

**Comment by liguanglin** [comment]
Hi，
1. for export mesh, you could try to add a [export_mesh](https://github.com/zju3dv/gcasp/blob/main/DualSDFHandler.py#L85) function after [optimizing shape](https://github.com/zju3dv/gcasp/blob/main/DualSDFHandler.py#L200).
2. maybe your test data path is empty, check your data path first.

**Comment by lwtai** [comment]
I solved my problem and also got reconstructed mesh, thanks for your response!
