### ISSUE TITLE
environment for reproduction 

### ISSUE THREAD

**Issue by jysh1023** [zju3dv/gcasp#13]
Hello, thank you for sharing your work.
Could you possibly share the environment requirement to reproduce the training results?

Thank you in advance

**Comment by liguanglin** [comment]
Hi, 
The core packages in environment I used before are:
torch==1.10.0+cu113
open3d==0.14.1
opencv-python==4.5.5.62
numpy==1.21.2
The above packages with other common python tools (like pyyaml, scipy ... ) are enough.

**Comment by jysh1023** [comment]
Thank you very much!
