### ISSUE TITLE
Pretrained weights?

### ISSUE THREAD

**Issue by HanzhiC** [zju3dv/gcasp#3]
Hi, Thanks for this nice work.
Could you provide pre-trained weights?
Thank you!

**Comment by liguanglin** [comment]
Hi, pre-trained weights for NOCS-real275 dataset can be download from [google drive](https://drive.google.com/file/d/1cznjCC8o3uHAfNPPnTSNZ9ONBFk1leDg/view?usp=sharing) described in [readme](https://github.com/zju3dv/gcasp#training). And the DualSDF weights can be download [here](https://drive.google.com/file/d/1d5DT51ZzB2UqMLkOIV5nhmBAjku8zaGS/view?usp=sharing) described in this [readme](https://github.com/liguanglin/DualSDF#data-preparation-for-nocs).
