### ISSUE TITLE
Question about primitive annotation

### ISSUE THREAD

**Issue by CNJianLiu** [zju3dv/gcasp#6]
Hi, thanks for releasing the great work! However, there is a problem when I generate the primitive annotation. When the program runs to 'mug', it will be interrupted as shown below. I don't know what caused this. Can you provide the primitive annotation you generated?

![image](https://user-images.githubusercontent.com/80870150/224869884-a151c15a-3113-4ff7-aed1-853b9bde98ac.png)

**Comment by liguanglin** [comment]
Hi, this is a error cause by open3d when loading texture. I have no idea how to fix this bug either. But you could try to remove all the material files first to run this script:
```
rm ./obj_models/train/*/*.mtl
python generate_primitives.py
```
And you can also download the primitives annotation from [here](https://drive.google.com/file/d/1IA2yEBtcUCaVnjXqJYEATAHBh4zO4IHP/view?usp=share_link), which I generate using the given pretrained DualSDF models.
