### ISSUE TITLE
Could you please provide a rough result about the time consuming？

### ISSUE THREAD

**Issue by lu-ming-lei** [zju3dv/gcasp#7]
I'm very impressed with your work! Can you provide some rough results about time consuming?
If possible, pose estimation part and mesh reconstruction part separately. Thanks a lot.

**Comment by liguanglin** [comment]
Hi, Thanks for interests in our work!
The time cost mainly depends on the shape optimization (see this [code](https://github.com/zju3dv/gcasp/blob/main/DualSDFHandler.py#L179)). I just tested it on my own computer with a 3060 grahpics card, the speed is about 11 objects per second, which means about 2 fps in NOCS dataset. The mesh is recovered using Marching Cubes after that and pose is computed from correspondences. I think the two steps' time could be ignored.

**Comment by lu-ming-lei** [comment]
Thanks for your quick reply！
It helps me a lot, thanks
