### ISSUE TITLE
关于测试结果

### ISSUE THREAD

**Issue by touchthefish233** [zju3dv/gcasp#8]
加载了预训练模型进行测试，跟文章中的结果有差距，请问是哪里复现错了吗？
![image](https://user-images.githubusercontent.com/68363637/234499266-f8581fe2-68a2-4c40-8262-69eeeaf3fa90.png)

**Comment by touchthefish233** [comment]
请问，训练的时候为什么没有借鉴SGPA的做法进行3：1的仿真和实拍数据集的采样呢？对实拍数据集，训练时使用实拍数据应该能获得更好的结果吧？

**Comment by liguanglin** [comment]
> 请问，训练的时候为什么没有借鉴SGPA的做法进行3：1的仿真和实拍数据集的采样呢？对实拍数据集，训练时使用实拍数据应该能获得更好的结果吧？

这个是因为nocs真实数据中的gt标定的不是很准确，会对我们用到分割真值的标注造成进一步的影响。我们在之前实验中试过，在real data上finetune之后，camera类的结果会有很大的提升，因为gt比较准确，并且和测试集中depth输入更加一致。其他类都会因为不准确的标注而丧失一部分精度。

关于上面结果的问题，我在3060的显卡上试了一下，发现结果和在2070 / v100上的结果差据很大，这个还需要进一步测试去找一下可能问题，请问是否可以提供一下你们测试的环境配置？

**Comment by touchthefish233** [comment]
非常感谢收到您的回复，我们是再A40上进行测试的。想问一下，怎么解决sgpa在实拍数据集上训练的时候，仿真实拍采样会溢出的问题？非常感谢

**Comment by touchthefish233** [comment]
非常感谢您的解答，这个问题很有趣啊

**Comment by liguanglin** [comment]
> 非常感谢收到您的回复，我们是再A40上进行测试的。想问一下，怎么解决sgpa在实拍数据集上训练的时候，仿真实拍采样会溢出的问题？非常感谢

这里可以详细描述一下“仿真实拍采样会溢出的问题”问题吗？我也不是很清楚sgpa存在哪些“会溢出”的问题。

**Comment by touchthefish233** [comment]
是这个地方，因为train_steps=8000，导致train_idx比数据集的长度大，且不能重复采样就会报错，想请教一下这个应该如何解决
![image](https://user-images.githubusercontent.com/68363637/234582007-f183ece9-a634-4357-baac-1071f6a38d19.png)

**Comment by touchthefish233** [comment]
请问可以看一下您实现的这一部分的代码吗？非常感谢！
![2MHNKU4`GGY17YXBCA19B`4](https://user-images.githubusercontent.com/68363637/234599258-60de9e63-cd4a-432b-996b-6eb26341db1c.png)

**Comment by liguanglin** [comment]
> 请问可以看一下您实现的这一部分的代码吗？非常感谢！ ![2MHNKU4GGY17YXBCA19B4](https://user-images.githubusercontent.com/68363637/234599258-60de9e63-cd4a-432b-996b-6eb26341db1c.png)

我觉得这个是python random.sample的问题，你可以尝试将random.sample改成random.choices试一下

**Comment by touchthefish233** [comment]
非常感谢！
